name: background_project
channels:
  - conda-forge
  - bioconda
  - defaults
dependencies:
  - python=3.11
  - cython<3
  - wheel
  - snakemake
  - hydra-core
  - mlflow
  - pandas
  - bowtie2
  - samtools
  - bwa
  - pysam>=0.23      # ‚Üê moved here (Conda layer)
  - pip
  - pip:
      - macs2